function DAAS_rule_decoder_part2_public_standalone(NewData2_DAAS, params, ruleselsummary)
% 
%
% DAAS_RULE_DECODER_PART2_PUBLIC_STANDALONE
%
% Public manuscript-figure version of the 2AFC rule-decoding analysis.
%
% This function performs within-day decoding of the active task rule
% (Rule 1 versus Rule 2) from trial-wise mean calcium activity. It uses
% processed calcium traces and the Part 1 rule-selectivity summary to
% compare decoder performance across neuronal categories.
%
% The code is intentionally restricted to manuscript figure outputs. It
% excludes exploratory plots, optional model variants, and print-only
% analyses that are not required to reproduce the paper figures.
%
% -------------------------------------------------------------------------
% Manuscript outputs generated by this function
% -------------------------------------------------------------------------
%   Fig. 7D / Fig. 7H
%       Decoder AUC across learning days using all neurons.
%
%   Fig. 7E / Fig. 7I
%       Sound-window versus early-post-sound decoder AUC for rule-preferring
%       and non-rule task-modulated neurons.
%
%   Supplementary Fig. 5D / Supplementary Fig. 5F
%       Per-day decoder AUC bars for Rule1, Rule2, and NonRule categories.
%
% -------------------------------------------------------------------------
% Expected inputs
% -------------------------------------------------------------------------
%   NewData2_DAAS
%       Processed data structure organized as:
%           NewData2_DAAS.(Animal).(Day){neuron}
%
%       Each neuron entry is expected to contain:
%           .data        [nTrials x nFrames] trial-wise calcium activity
%           .sound1Mask  logical vector for correct Rule 1 / Sound 1 trials
%           .sound2Mask  logical vector for correct Rule 2 / Sound 2 trials
%
%   params
%       Parameter structure. Required fields:
%           params.days
%           params.nFrames
%           params.fs
%           params.win.sound
%
%       Common decoder fields:
%           params.decoder.kfold
%           params.decoder.repeats
%           params.decoder.n_shuffles
%           params.decoder.save_dir
%
%   Summary
%       Optional Part 1 rule-selectivity summary table. If omitted, this
%       function tries to load a summary table from params.rule.save_dir.
%
% Notes:
%   This file is standalone in the MATLAB sense: the local helper functions
%   required by this analysis are included below the main function.

%% ------------------------------------------------------------------------
% 1. Parameters and defaults
% -------------------------------------------------------------------------

if nargin < 2
    params = struct();
end

days = getf(params, 'days', []);
if isempty(days)
    error('params.days is required, for example: {''One'',''Two'',''Three'',''Four'',''Five''}.');
end

T      = getf(params, 'nFrames', 89);
fs     = getf(params, 'fs', 16);
Wsound = getf(getf(params, 'win', struct()), 'sound', 32:40);

rule = getf(params, 'rule', struct());
correctOnly = getf(rule, 'correct_only', true);

% Directory containing the Part 1 rule-selectivity summary.
saveDir1 = getf(rule, 'save_dir', fullfile(pwd, 'rule_selectivity_public'));

% Decoder settings.
dec = getf(params, 'decoder', struct());
decDir = getf(dec, 'save_dir', fullfile(saveDir1, 'decoder_part2_public'));
if ~exist(decDir, 'dir')
    mkdir(decDir);
end

rngSeed = getf(dec, 'rng_seed', 42);
K = getf(dec, 'kfold', 5);
Nrep = getf(dec, 'repeats', 5);
Bnull = getf(dec, 'n_shuffles', 1000);
minCells = getf(dec, 'min_neurons', 1);
maxPerCls = getf(dec, 'max_trials_per_class', 150);

saveFigs = getf(dec, 'save_figs', true);
saveTables = getf(dec, 'save_tables', true);
closeFigs = getf(dec, 'close_figs', false);
figFormats = getf(dec, 'fig_formats', {'png'});

if ischar(figFormats) || isstring(figFormats)
    figFormats = cellstr(figFormats);
end

% Early window: first 0.5 s after the sound window.
tone_off = max(Wsound);
Wearly = tone_off + 1 : min(tone_off + round(0.5 * fs), T);

WinList = {'Sound', 'Early'};
Wbins = {clipW(Wsound, T), clipW(Wearly, T)};

% Decoder categories. Rule1/Rule2/NonRule are defined using the Part 1
% Sound-window rule-selectivity summary.
CATS = {'All', 'Rule1', 'Rule2', 'NonRule'};

fprintf('\n[Decoder public] Output directory: %s\n', decDir);
fprintf('[Decoder public] Sound window: frames %d-%d\n', min(Wsound), max(Wsound));
fprintf('[Decoder public] Early window: frames %d-%d\n', min(Wearly), max(Wearly));
fprintf('[Decoder public] CV: %d-fold, %d repeats, %d shuffles\n\n', K, Nrep, Bnull);

%% ------------------------------------------------------------------------
% 2. Load or standardize Part 1 summary
% -------------------------------------------------------------------------

if nargin < 3 || isempty(ruleselsummary)
    summaryFile = getf(dec, 'summary_file', '');

    candidateFiles = {};
    if ~isempty(summaryFile)
        candidateFiles{end+1} = summaryFile; %#ok<AGROW>
    end

    candidateFiles{end+1} = fullfile(saveDir1, 'source_rule_selectivity_summary_all_windows.csv');
    candidateFiles{end+1} = fullfile(saveDir1, 'source_sound_rule_summary_for_figures.csv');
    candidateFiles{end+1} = fullfile(saveDir1, 'rule_sel_summary.csv');

    loaded = false;
    for i = 1:numel(candidateFiles)
        if exist(candidateFiles{i}, 'file')
            ruleselsummary = readtable(candidateFiles{i});
            fprintf('[Decoder public] Loaded Part 1 summary: %s\n', candidateFiles{i});
            loaded = true;
            break;
        end
    end

    if ~loaded
        error(['No Summary table was provided and no summary file was found. ', ...
            'Pass Summary directly or set params.decoder.summary_file.']);
    end
end

ruleselsummary.animal = string(ruleselsummary.animal);
ruleselsummary.day = string(ruleselsummary.day);
ruleselsummary.window = string(ruleselsummary.window);

if ~ismember('sig_task', ruleselsummary.Properties.VariableNames)
    ruleselsummary.sig_task = false(height(ruleselsummary), 1);
end

%% ------------------------------------------------------------------------
% 3. Build decoder rows for each animal, day, window, and neuron category
% -------------------------------------------------------------------------
% For each animal/day/window/category:
%   1) build a trial-by-neuron feature matrix;
%   2) balance Rule 1 and Rule 2 trials;
%   3) train repeated cross-validated logistic classifiers;
%   4) compare observed AUC against label-shuffled null distributions.

Rows = table('Size', [0 17], 'VariableTypes', ...
    {'string','string','string','string','double','double','double','double','double','double','double','double','double','double','double','double','double'}, ...
    'VariableNames', {'animal','day','window','category','nTrials','nNeurons','auc_mean','auc_sem','acc_mean','acc_sem', ...
                      'p_shuffle','auc_null_mean','auc_null_sd','auc_med','auc_q1','auc_q3','nReps'});

NullStore = struct();

rng(rngSeed);
animals = fieldnames(NewData2_DAAS);

for ai = 1:numel(animals)
    animalName = animals{ai};

    if ~isstruct(NewData2_DAAS.(animalName))
        continue;
    end

    for di = 1:numel(days)
        dayName = days{di};

        if ~isfield(NewData2_DAAS.(animalName), dayName) || isempty(NewData2_DAAS.(animalName).(dayName))
            fprintf('[Decoder public] Skipping %s / %s: no data found.\n', animalName, dayName);
            continue;
        end

        E = NewData2_DAAS.(animalName).(dayName);

        [ruleLbl, srcIdx] = get_rule_labels(E, correctOnly);
        if isempty(ruleLbl)
            fprintf('[Decoder public] Skipping %s / %s: no rule labels found.\n', animalName, dayName);
            continue;
        end

        keep = ruleLbl == 1 | ruleLbl == 2;
        ruleLbl = ruleLbl(keep); %#ok<NASGU>

        SdaySound = ruleselsummary(ruleselsummary.animal == animalName & ruleselsummary.day == dayName & ruleselsummary.window == "Sound", :);
        catMask = build_category_masks(SdaySound, numel(E));

        for wi = 1:numel(WinList)
            windowName = WinList{wi};
            Wv = Wbins{wi};

            if isempty(Wv)
                continue;
            end

            try
                [X, y, okCols] = build_trial_feature_matrix(E, srcIdx, keep, Wv, T);
            catch ME
                warning('[Decoder public] Skipping %s / %s / %s: %s', ...
                    animalName, dayName, windowName, ME.message);
                continue;
            end

            if isempty(X)
                continue;
            end

            catHere = align_masks(catMask, okCols);

            for ci = 1:numel(CATS)
                categoryName = CATS{ci};
                colMask = catHere.(categoryName);

                if sum(colMask) < minCells
                    continue;
                end

                Xsub = X(:, colMask);
                [Xb, yb] = balance_classes(Xsub, y, maxPerCls);

                if numel(unique(yb)) < 2 || size(Xb, 1) < max(K, 10)
                    continue;
                end

                [auc_vec, acc_vec] = cv_decode_logistic(Xb, yb, K, Nrep);
                auc_null = shuffle_null_auc(Xb, yb, K, Bnull);

                r = table( ...
                    string(animalName), string(dayName), string(windowName), string(categoryName), ...
                    double(numel(yb)), double(size(Xb, 2)), ...
                    mean(auc_vec, 'omitnan'), sem(auc_vec), ...
                    mean(acc_vec, 'omitnan'), sem(acc_vec), ...
                    right_tail_p(mean(auc_vec, 'omitnan'), auc_null), ...
                    mean(auc_null, 'omitnan'), std(auc_null, 0, 'omitnan'), ...
                    median(auc_null, 'omitnan'), quantile(auc_null, 0.25), quantile(auc_null, 0.75), ...
                    double(numel(auc_vec)), ...
                    'VariableNames', Rows.Properties.VariableNames);

                Rows = [Rows; r]; %#ok<AGROW>

                key = matlab.lang.makeValidName(sprintf('%s__%s__%s', dayName, windowName, categoryName));
                if ~isfield(NullStore, key)
                    NullStore.(key) = [];
                end
                NullStore.(key) = [NullStore.(key); auc_null(:)];
            end
        end
    end
end

if isempty(Rows) || height(Rows) == 0
    error('No decoder rows were generated. Check the input data, Summary table, and decoder parameters.');
end

if saveTables
    writetable(Rows, fullfile(decDir, 'source_decoder_per_animal_rows.csv'));
end

fprintf('[Decoder public] Decoder rows generated: %d\n', height(Rows));

%% ------------------------------------------------------------------------
% 4. Aggregate decoder performance and compute figure statistics
% -------------------------------------------------------------------------

Agg = day_aggregate(Rows, NullStore);

if saveTables
    writetable(Agg, fullfile(decDir, 'source_decoder_day_summary.csv'));
end

print_decoder_agg_check(Agg, days);

% These statistics are used by the original figure functions for some
% annotations and are retained because they support manuscript figures.
stats = do_stats_and_print(Rows, days);

%% ------------------------------------------------------------------------
% 5. Generate manuscript figure outputs
% -------------------------------------------------------------------------

if saveFigs
    % Fig. 7D/H: all-neuron decoder AUC across days.
    run_figure_block('Fig7D_H_decoder_auc_across_days', @() ...
        save_public_figure(fig_decoder_auc_across_days(Agg, Rows, days, stats), decDir, ...
        'Fig7D_H_decoder_auc_across_days', figFormats, closeFigs));

    % Supplementary Fig. 5D/F: category-specific decoder AUC bars.
    run_figure_block('SuppFig5D_F_decoder_category_bars', @() ...
        save_public_figure(fig_decoder_category_bars(Agg, Rows, days, stats), decDir, ...
        'SuppFig5D_F_decoder_category_bars', figFormats, closeFigs));

    % Fig. 7E/I: Sound versus Early decoder AUC for rule-preferring and
    % non-rule task-modulated neurons.
    run_figure_block('Fig7E_I_decoder_sound_vs_early_rulepref_nonrule', @() ...
        save_public_figure(fig_decoder_sound_vs_early_rulepref_nonrule(Rows, days), decDir, ...
        'Fig7E_I_decoder_sound_vs_early_rulepref_nonrule', figFormats, closeFigs));
end

fprintf('\n[Decoder public] Finished manuscript decoder analysis.\n');
fprintf('[Decoder public] Outputs saved in: %s\n\n', decDir);

end

%% ========================================================================
% Public file-management helper functions
% ========================================================================

function run_figure_block(label, functionHandle)
% Run one manuscript-figure block and report clear warnings if it fails.

try
    fprintf('[Decoder public] Generating %s...\n', label);
    functionHandle();
catch ME
    warning('[Decoder public] %s failed: %s', label, ME.message);
end
end

function save_public_figure(h, saveDir, baseName, figFormats, closeFigs)
% Save a figure in one or more formats using manuscript-facing filenames.

if isempty(h) || ~ishandle(h)
    h = gcf;
end

for i = 1:numel(figFormats)
    ext = char(figFormats{i});
    ext = erase(ext, '.');
    outFile = fullfile(saveDir, sprintf('%s.%s', baseName, ext));
    saveas(h, outFile);
end

if closeFigs
    close(h);
end
end

%% ========================================================================
% Original local helper functions required by the public decoder pipeline
% ========================================================================
% These helper functions are copied from the original decoder analysis file
% so this public version can run as a single MATLAB file. The main function
% above only calls the helpers needed to generate the manuscript figures.

function [X, y, okCols] = build_trial_feature_matrix(E, srcIdx, keep, W, T, varargin)
% Returns a trial-by-neuron matrix (mean ΔF/F over W) on the largest common
% set of labeled trials shared by ALL usable neurons. Prints diagnostics.

    if nargin < 6 || isempty(varargin{1})
        if ~isfield(E{srcIdx}, 'sound1Mask') || ~isfield(E{srcIdx}, 'sound2Mask')
            error('build_trial_feature_matrix: source entry lacks sound1Mask/sound2Mask.');
        end
        s1 = logical(E{srcIdx}.sound1Mask);
        s2 = logical(E{srcIdx}.sound2Mask);
        L  = nan(size(s1));
        L(s1) = 1; L(s2) = 2;
        both = s1 & s2; if any(both), L(both) = 1; end
        ruleLblAll = L(:);
    else
        ruleLblAll = varargin{1}(:);
    end

    selIdx = find(keep);
    if isempty(selIdx)
        error('build_trial_feature_matrix: no labeled trials after KEEP mask.');
    end

    % usable neurons and their trial counts
    N = numel(E);
    usable = false(1,N);
    nTrialsEach = zeros(1,N);
    hasWin = false(1,N);
    for n = 1:N
        en = E{n};
        if ~isstruct(en) || ~isfield(en,'data') || isempty(en.data), continue; end
        [nTr, Tn] = size(en.data);
        if nTr > 0
            usable(n) = true;
            nTrialsEach(n) = nTr;
            hasWin(n) = any(W >= 1 & W <= Tn);
        end
    end
    if ~any(usable)
        error('build_trial_feature_matrix: no neurons have data.');
    end

    Nt_allSrc = numel(ruleLblAll);
    Nt_common = min([Nt_allSrc, min(nTrialsEach(usable))]);

    % DIAGNOSTICS header
    fprintf('[BTM] %s/%s/%s\n','(animal?)','(day?)','(window?)'); % filled by caller via logs above
    % Above line kept generic—your callsite already prints detailed headers.

    % small pretty print
    fprintf('      usableNeurons=%d / %d | withWindowOverlap=%d\n', sum(usable), N, sum(hasWin));
    Tnz = nTrialsEach(usable);
    fprintf('      per-neuron frames: min=%d, max=%d\n', T, T); %#ok<NASGU>
    fprintf('      labelLen=%d | minTrialsUsable=%d | Nt_common=%d\n', Nt_allSrc, min(nTrialsEach(usable)), Nt_common);

    if Nt_common <= 0
        error('build_trial_feature_matrix: no common trials across usable neurons.');
    end

    selIdxCommon = selIdx(selIdx <= Nt_common);
    if isempty(selIdxCommon)
        fprintf('[BTM][DIAG] — No labeled trials remain after common-span trim.\n');
        error('build_trial_feature_matrix: labeled trials exceed common trial span.');
    end
    y = ruleLblAll(selIdxCommon);
    fprintf('      labeledCorrectTrials=%d | afterCommonTrim=%d\n', numel(selIdx), numel(selIdxCommon));

    % assemble X
    nCols = sum(usable);
    X = nan(numel(selIdxCommon), nCols);
    okCols = false(1,N);
    col = 0;
    for n = 1:N
        if ~usable(n), continue; end
        en = E{n};
        [~, Tn] = size(en.data);
        Wc = W(W >= 1 & W <= Tn);
        if isempty(Wc), continue; end
        v = mean(en.data(1:Nt_common, Wc), 2, 'omitnan');   % [Nt_common x 1]
        fv = v(selIdxCommon);
        if all(~isfinite(fv)), continue; end
        col = col + 1;
        X(:, col) = fv;
        okCols(n) = true;
    end
    fprintf('      builtCols=%d | validRows=%d | class1=%d | class2=%d\n', col, size(X,1), sum(y==1), sum(y==2));

    X = X(:, 1:col);
    if isempty(X) || col==0
        fprintf('[BTM][DIAG] — No neurons yielded finite features in this window.\n');
        error('build_trial_feature_matrix: no neurons had usable data for the given window.');
    end
    validRows = all(isfinite(X), 2);
    X = X(validRows, :);
    y = y(validRows);

    if size(X,1) < 5 || numel(unique(y)) < 2 || size(X,2) < 2
        error('build_trial_feature_matrix: matrix too small after cleaning (rows=%d, cols=%d, classes=%d).', size(X,1), size(X,2), numel(unique(y)));
    end
end

function catMask = build_category_masks(SdaySnd, Nneurons)
% Using Part-1 Summary (SOUND window) to mark categories.
% IMPORTANT: 'All' must be true even if Summary is empty.

catMask = struct('All', true(Nneurons,1), ...   % <-- set All=true upfront
                 'Rule1', false(Nneurons,1), ...
                 'Rule2', false(Nneurons,1), ...
                 'NonRule', false(Nneurons,1));

if isempty(SdaySnd)
    % No info for Rule1/Rule2/NonRule; keep them false, but All stays true.
    return;
end

% Safety: ensure 'neuron' is valid indexing into 1..Nneurons
if ~ismember('neuron', SdaySnd.Properties.VariableNames)
    warning('Summary missing ''neuron'' column; only "All" category will be used.');
    return;
end

nList = double(SdaySnd.neuron(:));
validIdx = nList>=1 & nList<=Nneurons & isfinite(nList);
nList = nList(validIdx);

% Rule-pref (sig_FDR & auROC thresholds)
hasSigFDR = ismember('sig_FDR', SdaySnd.Properties.VariableNames);
hasAuROC  = ismember('auROC',  SdaySnd.Properties.VariableNames);
if ~(hasSigFDR && hasAuROC)
    warning('Summary missing sig_FDR/auROC; Rule1/Rule2 left empty.');
else
    r1_rows = SdaySnd.sig_FDR & SdaySnd.auROC>0.5;
    r2_rows = SdaySnd.sig_FDR & SdaySnd.auROC<0.5;
    r1_rows = r1_rows(validIdx);
    r2_rows = r2_rows(validIdx);
    catMask.Rule1(nList(r1_rows)) = true;
    catMask.Rule2(nList(r2_rows)) = true;
end

% Non-rule (sig_task & ~sig_FDR) if present
if ismember('sig_task', SdaySnd.Properties.VariableNames) && hasSigFDR
    nr_rows = SdaySnd.sig_task & ~SdaySnd.sig_FDR;
    nr_rows = nr_rows(validIdx);
    catMask.NonRule(nList(nr_rows)) = true;
end
end


function catHere = align_masks(catMask, okCols)
catHere = structfun(@(v) v(okCols), catMask, 'UniformOutput', false);
end

function [Xb, yb] = balance_classes(X, y, maxPerCls)
if nargin < 3 || isempty(maxPerCls), maxPerCls = Inf; end
idx1 = find(y==1); idx2 = find(y==2);
nmin = min(numel(idx1), numel(idx2));
nmin = min(nmin, maxPerCls);
if nmin < 1, Xb=[]; yb=[]; return; end
idx1 = idx1(randperm(numel(idx1), nmin));
idx2 = idx2(randperm(numel(idx2), nmin));
sel  = sort([idx1; idx2]);
Xb = X(sel, :);
yb = y(sel);
end

function [auc_vec, acc_vec] = cv_decode_logistic(X, y, K, Nrep)
auc_vec = zeros(Nrep,1);
acc_vec = zeros(Nrep,1);
y = double(y);  % labels {1,2}

for r = 1:Nrep
    try
        cv = cvpartition(categorical(y),'KFold',K);
    catch
        cv = cvpartition(numel(y),'KFold',K);
    end
    auc_f = zeros(K,1);
    acc_f = zeros(K,1);
    for k = 1:K
        trainIdx = training(cv,k);
        testIdx  = test(cv,k);
        Xtr = X(trainIdx,:); Xte = X(testIdx,:);
        ytr = y(trainIdx);   yte = y(testIdx);

        % standardize from train
        mu = mean(Xtr,1);  sd = std(Xtr,0,1);  sd(sd==0) = 1;
        Xtr = (Xtr - mu)./sd;  Xte = (Xte - mu)./sd;

        mdl = fitclinear(Xtr, ytr, 'Learner','logistic', ...
                         'Regularization','ridge','Lambda',1, ...
                         'ClassNames',[1 2]);
        [~,score] = predict(mdl, Xte);
        % score(:,2) is probability of class '2' for logistic
        s = score(:,2);
        auc_f(k) = quickAUC(s, yte==2);
        yhat = double(s >= 0.5) + 1; % map to {1,2}
        acc_f(k) = mean(yhat==yte);
    end
    auc_vec(r) = mean(auc_f,'omitnan');
    acc_vec(r) = mean(acc_f,'omitnan');
end
end

function auc = shuffle_null_auc(X, y, K, B)
auc = zeros(B,1);
for b = 1:B
    ysh = y(randperm(numel(y)));
    try
        cv = cvpartition(categorical(ysh),'KFold',K);
    catch
        cv = cvpartition(numel(ysh),'KFold',K);
    end
    auc_f = zeros(K,1);
    for k = 1:K
        tr = training(cv,k); te = test(cv,k);
        Xtr = X(tr,:); Xte = X(te,:); ytr = ysh(tr); yte = ysh(te);
        mu = mean(Xtr,1); sd = std(Xtr,0,1); sd(sd==0)=1;
        Xtr = (Xtr - mu)./sd;  Xte = (Xte - mu)./sd;
        mdl = fitclinear(Xtr, ytr, 'Learner','logistic', ...
                         'Regularization','ridge','Lambda',1, ...
                         'ClassNames',[1 2]);
        [~,score] = predict(mdl, Xte);
        auc_f(k) = quickAUC(score(:,2), yte==2);
    end
    auc(b) = mean(auc_f,'omitnan');
end
end

function a = quickAUC(scores, labelsLogical)
% Mann–Whitney U / rank-based AUC (fast, no perfcurve dependency)
labelsLogical = logical(labelsLogical);
sPos = scores(labelsLogical);
sNeg = scores(~labelsLogical);
if isempty(sPos) || isempty(sNeg)
    a = NaN; return;
end
r = tiedrank([sPos; sNeg]);
nPos = numel(sPos); nNeg = numel(sNeg);
Rpos = sum(r(1:nPos));
U = Rpos - nPos*(nPos+1)/2;
a = U / (nPos*nNeg);
end

function v = sem(x)
v = std(x,0,'omitnan')/max(1,sqrt(sum(isfinite(x))));
end

function p = right_tail_p(obs, nullAUC)
if isempty(nullAUC) || ~isfinite(obs), p = NaN; return; end
p = mean(nullAUC >= obs);
end

function v = getf(S, fld, default)
if nargin < 3, default = []; end
if isstruct(S) && isfield(S,fld) && ~isempty(S.(fld))
    v = S.(fld);
else
    v = default;
end
end

function Wc = clipW(W, T)
if isempty(W), Wc = [];
else, Wc = W(W >= 1 & W <= T);
end
end

function [ruleLbl, fromIdx] = get_rule_labels(E, correctOnly)
ruleLbl = []; fromIdx = [];
if isempty(E) || ~iscell(E), return; end
for n = 1:numel(E)
    en = E{n};
    if ~isstruct(en) || ~isfield(en,'data') || isempty(en.data), continue; end
    useAll = ~correctOnly && isfield(en,'sound1Mask_all') && isfield(en,'sound2Mask_all');
    if useAll
        s1 = logical(en.sound1Mask_all); s2 = logical(en.sound2Mask_all);
    elseif isfield(en,'sound1Mask') && isfield(en,'sound2Mask')
        s1 = logical(en.sound1Mask);     s2 = logical(en.sound2Mask);
    else
        continue;
    end
    L = nan(size(s1)); L(s1)=1; L(s2)=2; both = s1 & s2; if any(both), L(both)=1; end
    ruleLbl = L(:); fromIdx = n; return;
end
end

function Agg = day_aggregate(Rows, NullStore)
% Manual aggregator (no groupsummary). Returns table:
%   day, window, category, nModels, auc_mean, auc_sem, p_vs_shuffle
if isempty(Rows) || height(Rows)==0
    Agg = table('Size',[0 7], ...
        'VariableTypes',{'string','string','string','double','double','double','double'}, ...
        'VariableNames',{'day','window','category','nModels','auc_mean','auc_sem','p_vs_shuffle'});
    return;
end

Rows.day = string(Rows.day);
Rows.window = string(Rows.window);
Rows.category = string(Rows.category);

keys = unique(Rows(:,{'day','window','category'}),'rows');
n = height(keys);
Agg = table('Size',[n 7], ...
    'VariableTypes',{'string','string','string','double','double','double','double'}, ...
    'VariableNames',{'day','window','category','nModels','auc_mean','auc_sem','p_vs_shuffle'});

for i = 1:n
    d = keys.day(i); w = keys.window(i); c = keys.category(i);
    idx = Rows.day==d & Rows.window==w & Rows.category==c;
    vals = Rows.auc_mean(idx);
    Agg.day(i) = d; Agg.window(i) = w; Agg.category(i) = c;
    Agg.nModels(i) = sum(isfinite(vals));
    Agg.auc_mean(i) = mean(vals,'omitnan');
    Agg.auc_sem(i)  = std(vals,0,'omitnan')/max(1,sqrt(sum(isfinite(vals))));

    % ---- pooled shuffle-null p (supports both hierarchical and flattened keys)
    p = NaN;
    dkey = char(d); wkey = char(w); ckey = char(c);

    % try flattened "D__W__C"
    flatKey = matlab.lang.makeValidName(sprintf('%s__%s__%s', dkey, wkey, ckey));
    if isstruct(NullStore) && isfield(NullStore, flatKey)
        nullAUC = NullStore.(flatKey);
    elseif isstruct(NullStore) && isfield(NullStore, dkey) ...
          && isfield(NullStore.(dkey), wkey) ...
          && isfield(NullStore.(dkey).(wkey), ckey)
        nullAUC = NullStore.(dkey).(wkey).(ckey);
    else
        nullAUC = [];
    end

    mu = Agg.auc_mean(i);
    if ~isempty(nullAUC) && isfinite(mu)
        % two-sided around 0.5 (how far from chance)
        p = mean( abs(nullAUC - 0.5) >= abs(mu - 0.5) );
    end
    Agg.p_vs_shuffle(i) = p;
end
end

function h = fig_decoder_auc_across_days(Agg, Rows, days, stats)
if isempty(Agg) || height(Agg)==0
    h = figure('Name','Decoder AUC across days','Position',[80 80 1200 600],'Visible','on');
    tiledlayout(2,1); nexttile; axis off; title('No data'); nexttile; axis off; return;
end
Agg.day = string(Agg.day); Agg.window = string(Agg.window); Agg.category = string(Agg.category);
wins = ["Sound","Early"]; catsel = "All";

% --- define training days (Day1..Day5) ---
trainDays = string({'One','Two','Three','Four','Five'});

h = figure('Name','Decoder AUC across days','Position',[80 80 1200 600],'Visible','on');
tl = tiledlayout(2,1,'TileSpacing','compact','Padding','compact');
sgtitle(tl,'Decoder AUC across days (All neurons)','FontWeight','bold');

for r = 1:numel(wins)
    w = wins(r);
    ax = nexttile(tl,r); hold(ax,'on');

    % --- pull day means/SEMs from Agg for plotting ---
    S = Agg(Agg.window==w & Agg.category==catsel, :);

    y  = nan(1,numel(days)); e = y; p = y;
    for k=1:numel(days)
        idx = find(S.day==string(days{k}), 1);
        if ~isempty(idx), y(k)=S.auc_mean(idx); e(k)=S.auc_sem(idx); p(k)=S.p_vs_shuffle(idx); end
    end

    finiteMask = isfinite(y) & isfinite(e);
    if any(finiteMask)
        xx = find(finiteMask);
        errorbar(ax, xx, y(finiteMask), e(finiteMask), 'o-','LineWidth',1.6,'MarkerSize',6);
        yline(ax, 0.5,'k--');
        xticks(ax, 1:numel(days)); xticklabels(ax, days);

        valsLow  = y(finiteMask)-e(finiteMask);
        valsHigh = y(finiteMask)+e(finiteMask);
        lo = min([0.45; valsLow(:)]) - 0.02; hi = max([0.90; valsHigh(:)]) + 0.02;
        ylim(ax, [lo hi]); ylabel(ax,'AUC');
        grid(ax,'on');

        % --- per-day stars vs shuffle ---
        for k=xx(:).'
            if isfinite(p(k)) && p(k) < 0.05
                text(ax, k, y(k)+e(k)+0.015, p2stars_(p(k)), ...
                    'HorizontalAlignment','center','FontSize',11,'FontWeight','bold');
            end
        end

        % --- Trend p in title (if present) ---
        trendP = NaN;
        if exist('stats','var') && isstruct(stats) && isfield(stats,'trend') && isfield(stats.trend, char(w))
            trendP = stats.trend.(char(w)).p;
        end

        % =========================================================
        % NEW: Day1–Day5 learning test using Rows (per-animal values)
        % Method preference:
        %   1) Friedman (repeated-measures) if enough complete animals
        %   2) LME (random intercept animal) if fitlme exists
        %   3) Kruskal–Wallis fallback (warn: ignores repeated measures)
        % =========================================================
        pLearn = NaN; learnLabel = ""; didLearn = false;

        if exist('Rows','var') && istable(Rows) && height(Rows)>0
            R = Rows;

            % types
            R.animal   = string(R.animal);
            R.day      = string(R.day);
            R.window   = string(R.window);
            R.category = string(R.category);

            Rw = R(R.window==w & R.category==catsel & ismember(R.day, trainDays), :);

            if height(Rw) > 0
                animals = unique(Rw.animal);
                % build animals x 5 matrix
                M = nan(numel(animals), numel(trainDays));
                for ai = 1:numel(animals)
                    a = animals(ai);
                    for di = 1:numel(trainDays)
                        dname = trainDays(di);
                        ii = find(Rw.animal==a & Rw.day==dname, 1, 'first');
                        if ~isempty(ii), M(ai,di) = Rw.auc_mean(ii); end
                    end
                end

                % --- Friedman if enough complete rows ---
                complete = all(isfinite(M), 2);
                Mc = M(complete,:);
                if size(Mc,1) >= 5
                    didLearn = true;
                    [pLearn, tbl] = friedman(Mc, 1, 'off');
                    chi2 = tbl{2,5};
                    df   = tbl{2,3};
                    learnLabel = sprintf('Friedman \\chi^2(%d)=%.3f, p=%.3g %s (n=%d animals)', ...
                        df, chi2, pLearn, p2stars_(pLearn), size(Mc,1));

                    fprintf('--- LEARNING (Decoder AUC) %s window ---\n', char(w));
                    fprintf('Day1–Day5 (Friedman, complete cases): chi2(%d)=%.3f, p=%.4g %s  [n=%d animals]\n', ...
                        df, chi2, pLearn, char(p2stars_(pLearn)), size(Mc,1));

                elseif exist('fitlme','file')==2
                    % --- LME fallback (handles missing days) ---
                    didLearn = true;
                    T = table;
                    T.auc = Rw.auc_mean;
                    % map day -> 1..5
                    T.dayIndex = nan(height(Rw),1);
                    for i=1:height(Rw)
                        T.dayIndex(i) = find(trainDays==Rw.day(i), 1);
                    end
                    T.animal = categorical(Rw.animal);

                    lme = fitlme(T, 'auc ~ 1 + dayIndex + (1|animal)');
                    ct = lme.Coefficients;
                    rr = strcmp(ct.Name,'dayIndex');

                    pLearn = ct.pValue(rr);
                    beta   = ct.Estimate(rr);
                    learnLabel = sprintf('LME beta=%.4f, p=%.3g %s (n=%d rows)', ...
                        beta, pLearn, p2stars_(pLearn), height(T));

                    fprintf('--- LEARNING (Decoder AUC) %s window ---\n', char(w));
                    fprintf('Day1–Day5 (LME): beta=%.4f, p=%.4g %s  [rows=%d, animals=%d]\n', ...
                        beta, pLearn, char(p2stars_(pLearn)), height(T), numel(unique(Rw.animal)));

                else
                    % --- KW last resort (not ideal for repeated measures) ---
                    vals = Rw.auc_mean;
                    grp  = nan(height(Rw),1);
                    for i=1:height(Rw), grp(i) = find(trainDays==Rw.day(i), 1); end
                    ok = isfinite(vals) & isfinite(grp);
                    if sum(ok) >= 6 && numel(unique(grp(ok))) >= 2
                        didLearn = true;
                        [pLearn, tbl] = kruskalwallis(vals(ok), grp(ok), 'off');
                        chi2 = tbl{2,5};
                        df   = tbl{2,3};
                        learnLabel = sprintf('KW \\chi^2(%d)=%.3f, p=%.3g %s', ...
                            df, chi2, pLearn, p2stars_(pLearn));

                        fprintf('--- LEARNING (Decoder AUC) %s window ---\n', char(w));
                        fprintf('Day1–Day5 (KW, WARNING: ignores repeated-measures): chi2(%d)=%.3f, p=%.4g %s\n', ...
                            df, chi2, pLearn, char(p2stars_(pLearn)));
                    end
                end
            end
        end

        % --- overlay learning text + bracket One→Five ---
        if didLearn && isfinite(pLearn)
            text(ax, 0.02, 0.92, ['Day1–5: ' learnLabel], ...
                'Units','normalized','HorizontalAlignment','left','VerticalAlignment','top', ...
                'FontWeight','bold','FontSize',10);

            idOne  = find(strcmp(days,'One'), 1);
            idFive = find(strcmp(days,'Five'), 1);
            if ~isempty(idOne) && ~isempty(idFive)
                ymax = max(y(finiteMask)+e(finiteMask), [], 'omitnan');
                yb = ymax + 0.045;
                draw_bracket(ax, idOne, idFive, yb, p2stars_(pLearn));
            end
        end

        % --- title ---
        if isfinite(trendP)
            title(ax, sprintf('%s window (trend p=%.3g)', w, trendP));
        else
            title(ax, sprintf('%s window', w));
        end

        % --- your existing Five vs Reversal bracket (kept) ---
        idFive = find(strcmp(days,'Five')); idRev = find(strcmp(days,'Reversal'));
        if ~isempty(idFive) && ~isempty(idRev) && any(isfinite([y(idFive) y(idRev)]))
            ymax = max([y(idFive)+e(idFive), y(idRev)+e(idRev)], [], 'omitnan');
            yb = ymax + 0.025;
            if exist('stats','var') && isstruct(stats) && isfield(stats,'day5rev') && isfield(stats.day5rev, char(w))
                p5r = stats.day5rev.(char(w)).p;
                if isfinite(p5r)
                    draw_bracket(ax, idFive, idRev, yb, p2stars_(p5r));
                end
            end
        end

    else
        axis(ax,'off'); title(ax, sprintf('%s window — no decodable models', w));
    end
end
end




function h = fig_decoder_category_bars(Agg, Rows, days, stats)
if isempty(Agg) || height(Agg)==0
    h = figure('Name','Decoder per-day categories','Position',[80 80 1400 650],'Visible','on');
    tiledlayout(2,1); nexttile; axis off; title('No data'); nexttile; axis off; return;
end
Agg.day = string(Agg.day); Agg.window = string(Agg.window); Agg.category = string(Agg.category);

catplot = ["Rule1","Rule2","NonRule"];
winlist = ["Sound","Early"];

h = figure('Name','Decoder per-day categories','Position',[80 80 1400 650],'Visible','on');
tl = tiledlayout(2,1,'TileSpacing','compact','Padding','compact');
sgtitle(tl,'Decoder AUC by category per day','FontWeight','bold');

for r = 1:numel(winlist)
    w = winlist(r);
    nexttile(tl,r); hold on;

    Y = nan(numel(days), numel(catplot));
    E = nan(size(Y));
    P = nan(size(Y));
    for di = 1:numel(days)
        for cj = 1:numel(catplot)
            s = Agg(Agg.window==w & Agg.day==string(days{di}) & Agg.category==catplot(cj), :);
            if ~isempty(s)
                Y(di,cj) = s.auc_mean(1);
                E(di,cj) = s.auc_sem(1);
                P(di,cj) = s.p_vs_shuffle(1);
            end
        end
    end

    if ~any(isfinite(Y),'all')
        axis off; title(sprintf('%s window — no category data', w));
        continue;
    end

    Yplot = Y; Yplot(~isfinite(Yplot)) = 0;
    bh = bar(Yplot, 'grouped');
    yline(0.5,'k--');
    xticks(1:numel(days)); xticklabels(days);

    valsLow  = (Y - E); valsHigh = (Y + E);
vLow  = reshape(valsLow(isfinite(valsLow)),  [], 1);
vHigh = reshape(valsHigh(isfinite(valsHigh)), [], 1);
lo = min([0.45; vLow; 0.5]) - 0.02;
hi = max([0.90; vHigh; 0.5]) + 0.02;
    ylim([lo hi]);
    ylabel('AUC'); title(sprintf('%s window', w));
    legend(catplot,'Location','eastoutside'); grid on;

    ngroups = size(Y,1); nbars = size(Y,2);
    x = nan(ngroups, nbars);
    for b = 1:nbars, x(:,b) = bh(b).XEndPoints; end

    % error bars + per-bar shuffle stars
    for di = 1:ngroups
        for cj = 1:nbars
            if isfinite(Y(di,cj)) && isfinite(E(di,cj))
                errorbar(x(di,cj), Y(di,cj), E(di,cj), 'k', 'linestyle','none','LineWidth',1.1);
                if isfinite(P(di,cj)) && P(di,cj) < 0.05
                    text(x(di,cj), Y(di,cj)+E(di,cj)+0.015, p2stars_(P(di,cj)), ...
                        'HorizontalAlignment','center','FontSize',10,'FontWeight','bold');
                end
            end
        end
    end

    % NEW: within-day category contrasts (paired across animals)
    for di = 1:ngroups
        d = string(days{di});
        yTop = max(Y(di,:)+E(di,:),[],'omitnan');

        if isfield(stats,'cats') && isfield(stats.cats, char(w)) && isfield(stats.cats.(char(w)), char(d))
            C = stats.cats.(char(w)).(char(d));

            % R1 vs R2 (two-sided)
            if isfield(C,'p_r1r2') && isfinite(C.p_r1r2)
                xpos1 = x(di,1); xpos2 = x(di,2);
                yb = yTop + 0.03;
                draw_bracket(gca, xpos1, xpos2, yb, p2stars_(C.p_r1r2));
                yTop = yb; % stack if needed
            end

            % (R1+R2)/2 vs NonRule (right-tailed)
            if isfield(C,'p_r12nr') && isfinite(C.p_r12nr)
                xpos1 = mean([x(di,1), x(di,2)], 'omitnan'); 
                xpos2 = x(di,3);
                yb = yTop + 0.03;
                draw_bracket(gca, xpos1, xpos2, yb, p2stars_(C.p_r12nr));
            end
        end
    end
end
end


function s = p2stars_(p)
    if ~isfinite(p), s = "ns"; return; end
    if p < 1e-3, s = "***";
    elseif p < 1e-2, s = "**";
    elseif p < 0.05, s = "*";
    else, s = "ns";
    end
end

function print_decoder_agg_check(Agg, days)
if isempty(Agg) || height(Agg)==0
    fprintf('[Decoder Part2] Agg is EMPTY\n'); return;
end
Agg.day = string(Agg.day); Agg.window = string(Agg.window); Agg.category = string(Agg.category);
wins = ["Sound","Early"]; cats = ["All","Rule1","Rule2","NonRule"];
for w = wins
    fprintf('--- %s ---\n', w);
    for d = 1:numel(days)
        dd = string(days{d});
        rowAll = Agg(Agg.window==w & Agg.day==dd & Agg.category=="All",:);
        rowR1  = Agg(Agg.window==w & Agg.day==dd & Agg.category=="Rule1",:);
        rowR2  = Agg(Agg.window==w & Agg.day==dd & Agg.category=="Rule2",:);
        rowNR  = Agg(Agg.window==w & Agg.day==dd & Agg.category=="NonRule",:);
        fprintf('%s: All(%d) R1(%d) R2(%d) NR(%d)\n', dd, ...
            ~isempty(rowAll) && isfinite(rowAll.auc_mean), ...
            ~isempty(rowR1)  && isfinite(rowR1.auc_mean), ...
            ~isempty(rowR2)  && isfinite(rowR2.auc_mean), ...
            ~isempty(rowNR)  && isfinite(rowNR.auc_mean));
    end
end
end

function stats = do_stats_and_print(R, days)
% Standardizes types and prints:
%  - Spearman trend of AUC (All) across days
%  - Paired Five vs Reversal (All)
%  - Per-day Rule1 vs Rule2
%  - Per-day (avg Rule1&Rule2) vs NonRule
%
% Returns a struct "stats" with the same numbers.

    % --- Make types consistent (fixes your ismember error) ---
    if ~isstring(R.day),      R.day      = string(R.day);      end
    if ~isstring(R.window),   R.window   = string(R.window);   end
    if ~isstring(R.category), R.category = string(R.category); end
    if ismember('animal', R.Properties.VariableNames) && ~isstring(R.animal)
        R.animal = string(R.animal);
    end

    wins = ["Sound","Early"];
    stats = struct;

    for wi = 1:numel(wins)
        w = wins(wi);

        % ---------- Trend across days (All) ----------
        S = R(R.window==w & R.category=="All" & ismember(R.day, string(days)), :);
        if ~isempty(S)
            % map days -> numeric order 1..N
            [tf, idx] = ismember(S.day, string(days));
            S = S(tf,:); idx = idx(tf);
            if ~isempty(idx)
                try
                    [rho,p] = corr(idx(:), S.auc_mean(:), 'Type','Spearman', 'Rows','complete');
                catch
                    % very old MATLAB fall-back: rank-transform
                    [~,ri] = sort(idx(:)); [~,ri] = sort(ri);
                    [~,ra] = sort(S.auc_mean(:)); [~,ra] = sort(ra);
                    [rho,p] = corr(ri, ra, 'Rows','complete');
                end
                fprintf('[STATS] %s — Trend All across days: rho=%.3f, p=%.4g %s (n=%d)\n', ...
                        w, rho, p, p2stars_(p), numel(idx));
                stats.(w).trend = struct('rho',rho,'p',p,'n',numel(idx));
            end
        end

        % ---------- Five vs Reversal (All) ----------
        S5 = R(R.window==w & R.category=="All" & R.day=="Five",      {'animal','auc_mean'});
        SR = R(R.window==w & R.category=="All" & R.day=="Reversal",  {'animal','auc_mean'});
        if ~isempty(S5) && ~isempty(SR)
            [aa, i5, iR] = intersect(S5.animal, SR.animal);
            if ~isempty(aa)
                x = S5.auc_mean(i5);  % Five
                y = SR.auc_mean(iR);  % Reversal
                test = 'signrank';
                try
                    p = signrank(x, y);   % paired
                catch
                    p = ranksum(x, y); test = 'ranksum';
                end
                dmed = median(x - y, 'omitnan');
                fprintf('[STATS] %s — Five vs Reversal (All): Δmedian=%.3f, p=%.4g %s (n=%d) [%s]\n', ...
                        w, dmed, p, p2stars_(p), numel(aa), test);
                stats.(w).five_vs_rev = struct('n',numel(aa),'medianDelta',dmed,'p',p,'test',test);
            end
        end

        % ---------- Per-day Rule1 vs Rule2 & (R1&R2) vs NonRule ----------
        for di = 1:numel(days)
            dd = string(days{di});
            T1  = R(R.window==w & R.day==dd & R.category=="Rule1",   {'animal','auc_mean'});
            T2  = R(R.window==w & R.day==dd & R.category=="Rule2",   {'animal','auc_mean'});
            TNR = R(R.window==w & R.day==dd & R.category=="NonRule", {'animal','auc_mean'});

            % R1 vs R2 (paired by animal)
            if ~isempty(T1) && ~isempty(T2)
                [aa, i1, i2] = intersect(T1.animal, T2.animal);
                if numel(aa) >= 3
                    x = T1.auc_mean(i1); y = T2.auc_mean(i2);
                    test = 'signrank';
                    try, p12 = signrank(x, y); catch, p12 = ranksum(x, y); test = 'ranksum'; end
                    dmed = median(x - y, 'omitnan');
                    fprintf('[STATS] %s — %s: R1 vs R2: Δmedian=%.3f, p=%.4g %s (n=%d) [%s]\n', ...
                            w, dd, dmed, p12, p2stars_(p12), numel(aa), test);
                    stats.(w).(dd).R1vR2 = struct('n',numel(aa),'medianDelta',dmed,'p',p12,'test',test);
                end
            end

            % (R1&R2 avg) vs NonRule (paired by animal where NonRule present)
            if ~isempty(TNR) && (~isempty(T1) || ~isempty(T2))
                A = unique([T1.animal; T2.animal]);
                if ~isempty(A)
                    % average R1/R2 per animal when present
                    [tf1, j1] = ismember(A, T1.animal); r1 = nan(numel(A),1); r1(tf1) = T1.auc_mean(j1(tf1));
                    [tf2, j2] = ismember(A, T2.animal); r2 = nan(numel(A),1); r2(tf2) = T2.auc_mean(j2(tf2));
                    rr = nanmean([r1 r2], 2);

                    [aa, iR, iN] = intersect(A, TNR.animal);
                    x = rr(iR); y = TNR.auc_mean(iN);
                    m = isfinite(x) & isfinite(y);
                    if sum(m) >= 3
                        test = 'signrank';
                        try, pRN = signrank(x(m), y(m)); catch, pRN = ranksum(x(m), y(m)); test = 'ranksum'; end
                        dmed = median(x(m) - y(m), 'omitnan');
                        fprintf('[STATS] %s — %s: (R1&R2) vs NonRule: Δmedian=%.3f, p=%.4g %s (n=%d) [%s]\n', ...
                                w, dd, dmed, pRN, p2stars_(pRN), sum(m), test);
                        stats.(w).(dd).R12vNR = struct('n',sum(m),'medianDelta',dmed,'p',pRN,'test',test);
                    end
                end
            end
        end
    end
end


function q = bh_fdr_local(p)
p = p(:); v = isfinite(p);
q = nan(size(p));
if any(v)
    try
        q(v) = mafdr(p(v),'BHFDR',true);
    catch
        % fallback BH
        x = p(v);
        [xs,idx] = sort(x);
        m = numel(xs); r = (1:m)';
        qtmp = xs.*m./r;
        for i=m-1:-1:1, qtmp(i) = min(qtmp(i), qtmp(i+1)); end
        y = nan(size(xs)); y(idx)=min(qtmp,1);
        q(v)=y;
    end
end
end

function draw_bracket(ax, x1, x2, y, label)
% Draw a simple significance bracket between x1 and x2 at height y
hold(ax,'on');
plot(ax, [x1 x1 x2 x2], [y-0.005 y y y-0.005], 'k','LineWidth',1);
text(ax, mean([x1,x2]), y+0.006, label, 'HorizontalAlignment','center', ...
     'FontSize',11,'FontWeight','bold');
end

function stats = do_clustered_pool_tests(R, days)
% Cluster-aware tests using animal as the independent unit.
% Uses all available days to stabilize estimates within animal.

trainDays = string({'One','Two','Three','Four','Five'});
wins      = string({'Sound','Early'});

% ensure strings
R.animal   = string(R.animal);
R.day      = string(R.day);
R.window   = string(R.window);
R.category = string(R.category);

animals = unique(R.animal);
stats = struct();

for wi = 1:numel(wins)
    w = wins(wi);

    %% (A) Trend across training days (All neurons), per-animal Spearman, then signrank vs 0
    rho_list = [];
    for ai = 1:numel(animals)
        a = animals(ai);
        idx = R.animal==a & R.window==w & R.category=="All" & ismember(R.day, trainDays);
        if any(idx)
            dnames = R.day(idx);
            yvals  = R.auc_mean(idx);
            % align to numeric day order 1..5
            [ok, di] = ismember(dnames, trainDays);
            di = di(ok); yv = yvals(ok);
            % guard: need >=3 points for a meaningful rho
            if numel(di) >= 3
                [rho,~] = corr(di(:), yv(:), 'Type','Spearman','Rows','complete');
                if isfinite(rho), rho_list(end+1,1) = rho; end %#ok<AGROW>
            end
        end
    end
    p_trend = NaN; med_rho = NaN; n_trend = numel(rho_list);
    if n_trend >= 1
        try
            p_trend = signrank(rho_list, 0);
        catch
            % fallback: binomial sign test
            s = sum(rho_list>0);
            p_trend = 2*binocdf(min(s, n_trend-s), n_trend, 0.5);
        end
        med_rho = median(rho_list,'omitnan');
    end
    stats.(w).trend = struct('n',n_trend,'median_rho',med_rho,'p',p_trend);

    %% (B) Five vs Reversal (All neurons), paired within animal
    deltas = nan(numel(animals),1);
    for ai = 1:numel(animals)
        a = animals(ai);
        y5 = mean(R.auc_mean(R.animal==a & R.window==w & R.category=="All" & R.day=="Five"),'omitnan');
        yR = mean(R.auc_mean(R.animal==a & R.window==w & R.category=="All" & R.day=="Reversal"),'omitnan');
        if isfinite(y5) && isfinite(yR)
            deltas(ai) = y5 - yR;
        end
    end
    val = deltas(isfinite(deltas));
    p_pair = NaN; med_delta = NaN;
    if ~isempty(val)
        try
            p_pair = signrank(val, 0);
        catch
            s = sum(val>0); nN = numel(val);
            p_pair = 2*binocdf(min(s, nN-s), nN, 0.5);
        end
        med_delta = median(val,'omitnan');
    end
    stats.(w).five_vs_rev = struct('n',numel(val),'median_delta',med_delta,'p',p_pair);

    %% (C) Rule1 vs Rule2 (average across training days, per animal)
    deltas = nan(numel(animals),1);
    for ai = 1:numel(animals)
        a = animals(ai);
        r1 = mean(R.auc_mean(R.animal==a & R.window==w & R.category=="Rule1" & ismember(R.day,trainDays)), 'omitnan');
        r2 = mean(R.auc_mean(R.animal==a & R.window==w & R.category=="Rule2" & ismember(R.day,trainDays)), 'omitnan');
        if isfinite(r1) && isfinite(r2)
            deltas(ai) = r1 - r2;
        end
    end
    val = deltas(isfinite(deltas));
    p12 = NaN; med12 = NaN;
    if ~isempty(val)
        try
            p12 = signrank(val, 0);
        catch
            s = sum(val>0); nN = numel(val);
            p12 = 2*binocdf(min(s, nN-s), nN, 0.5);
        end
        med12 = median(val,'omitnan');
    end
    stats.(w).r1_vs_r2 = struct('n',numel(val),'median_delta',med12,'p',p12);

    %% (D) (Rule-pref avg) vs Non-rule (average across training days, per animal)
    deltas = nan(numel(animals),1);
    for ai = 1:numel(animals)
        a = animals(ai);
        r1 = mean(R.auc_mean(R.animal==a & R.window==w & R.category=="Rule1"   & ismember(R.day,trainDays)),'omitnan');
        r2 = mean(R.auc_mean(R.animal==a & R.window==w & R.category=="Rule2"   & ismember(R.day,trainDays)),'omitnan');
        nr = mean(R.auc_mean(R.animal==a & R.window==w & R.category=="NonRule"& ismember(R.day,trainDays)),'omitnan');
        rp = mean([r1 r2],'omitnan');
        if isfinite(rp) && isfinite(nr)
            deltas(ai) = rp - nr;
        end
    end
    val = deltas(isfinite(deltas));
    pRN = NaN; medRN = NaN;
    if ~isempty(val)
        try
            pRN = signrank(val, 0);
        catch
            s = sum(val>0); nN = numel(val);
            pRN = 2*binocdf(min(s, nN-s), nN, 0.5);
        end
        medRN = median(val,'omitnan');
    end
    stats.(w).rulepref_vs_nonrule = struct('n',numel(val),'median_delta',medRN,'p',pRN);
end
end

function print_clustered_pool_stats(stats)
wins = fieldnames(stats);
for i = 1:numel(wins)
    w = wins{i};
    t  = stats.(w).trend;
    fr = stats.(w).five_vs_rev;
    r12= stats.(w).r1_vs_r2;
    rn = stats.(w).rulepref_vs_nonrule;

    fprintf('[CLUSTER] %s — Trend (All, One–Five): median ρ=%.3f, p=%.4g %s (n=%d)\n', ...
        w, t.median_rho, t.p, char(p2stars_(t.p)), t.n);

    fprintf('[CLUSTER] %s — Five vs Reversal (All): Δmedian=%.3f, p=%.4g %s (n=%d)\n', ...
        w, fr.median_delta, fr.p, char(p2stars_(fr.p)), fr.n);

    fprintf('[CLUSTER] %s — Rule1 vs Rule2 (train avg): Δmedian=%.3f, p=%.4g %s (n=%d)\n', ...
        w, r12.median_delta, r12.p, char(p2stars_(r12.p)), r12.n);

    fprintf('[CLUSTER] %s — (Rule-pref avg) vs Non-rule (train avg): Δmedian=%.3f, p=%.4g %s (n=%d)\n', ...
        w, rn.median_delta, rn.p, char(p2stars_(rn.p)), rn.n);
end
end


function neuron_level_LME(ruleselsummary, days)
% Mixed-effects on per-neuron tuning STRENGTH (magnitude), not signed auROC.
% Windows: Sound/Early. Random intercept per animal.
% Prints:
%  - Training trend (One–Five): β and p on strength
%  - Five vs Reversal: Δstrength and p
%  - Rule-pref (Rule1|Rule2) vs Non-Rule during training: Δstrength and p

if exist('fitlme','file')~=2
    warning('fitlme not found; skipping neuron-level mixed-effects.');
    return;
end

S = ruleselsummary;
need = ismember({'animal','day','window','auROC'}, S.Properties.VariableNames);
if ~all(need)
    warning('Summary lacks required columns (animal/day/window/auROC).'); return;
end

% Keep finite auROC and target windows
S = S( (S.window=="Sound" | S.window=="Early") & isfinite(S.auROC), :);

% Build category from Part-1 if available
S.category = repmat("NonRule", height(S),1);
hasFDR  = ismember('sig_FDR',  S.Properties.VariableNames);
hasTask = ismember('sig_task', S.Properties.VariableNames);
if hasFDR
    S.category(S.sig_FDR & S.auROC>0.5) = "Rule1";
    S.category(S.sig_FDR & S.auROC<0.5) = "Rule2";
    if hasTask
        S.category(~S.sig_FDR & S.sig_task) = "NonRule";
    end
end

% Categorical coercion
S.animal = categorical(string(S.animal));
S.day    = categorical(string(S.day));
S.window = categorical(string(S.window));

% Day index 1..5
trainDaysStr = string(days);
trainDaysCat = categorical(trainDaysStr);
dmap = containers.Map(cellstr(trainDaysStr), 1:numel(trainDaysStr));
S.dayIndex = nan(height(S),1);
for i=1:height(S)
    k = char(string(S.day(i)));
    if isKey(dmap,k), S.dayIndex(i) = dmap(k); end
end

% ---- ALIGN & MAGNITUDE ----
S.aligned = S.auROC;                 % align Rule2 upward
isR2 = (S.category=="Rule2");
S.aligned(isR2) = 1 - S.aligned(isR2);
S.strength = abs(S.aligned - 0.5);   % 0..0.5, larger = stronger tuning

for w = ["Sound","Early"]
    Sw = S(S.window==categorical(w), :);

    % (i) Training trend (One–Five), All neurons (exclude Reversal)
    Tmask = Sw.day ~= categorical("Reversal") & ismember(Sw.day, trainDaysCat);
    T = Sw(Tmask, :);
    if height(T) >= 50 && all(isfinite(T.dayIndex))
        lme = fitlme(T, 'strength ~ 1 + dayIndex + (1|animal)');
        ct  = lme.Coefficients; r = strcmp(ct.Name,'dayIndex');
        if any(r)
            fprintf('[NEURON-LME MAG] %s — Trend (All strength): beta=%.4f, p=%.4g\n', ...
                char(w), ct.Estimate(r), ct.pValue(r));
        end
    end

    % (ii) Five vs Reversal (All neurons), on strength
    Fmask = ismember(Sw.day, categorical(["Five","Reversal"]));
    F = Sw(Fmask, :);
    if height(F) >= 30
        F.isReversal = double(F.day==categorical("Reversal"));
        lme = fitlme(F, 'strength ~ 1 + isReversal + (1|animal)');
        ct  = lme.Coefficients; r = strcmp(ct.Name,'isReversal');
        if any(r)
            fprintf('[NEURON-LME MAG] %s — Five vs Reversal (All strength): Δ=%.4f, p=%.4g\n', ...
                char(w), ct.Estimate(r), ct.pValue(r));
        end
    end

    % (iii) Rule-pref vs Non-rule during training, on strength
    Rmask = Sw.day ~= categorical("Reversal") & ismember(Sw.day, trainDaysCat) & ...
            ismember(Sw.category, ["Rule1","Rule2","NonRule"]);
    R = Sw(Rmask, :);
    if height(R) >= 30 && all(isfinite(R.dayIndex))
        R.RulePref = double(R.category=="Rule1" | R.category=="Rule2");
        lme = fitlme(R, 'strength ~ 1 + RulePref + dayIndex + (1|animal)');
        ct  = lme.Coefficients; r = strcmp(ct.Name,'RulePref_true');
        if ~any(r), r = strcmp(ct.Name,'RulePref'); end
        if any(r)
            fprintf('[NEURON-LME MAG] %s — Rule-pref vs Non-rule (strength): Δ=%.4f, p=%.4g\n', ...
                char(w), ct.Estimate(r), ct.pValue(r));
        end
    end
end
end

function h = fig_decoder_sound_vs_early_rulepref_nonrule(R, days)
% Plot decoder performance in the Sound and Early windows.
%
% Left panel:
%   Rule-preferring neurons, computed as the within-animal average of the
%   Rule1 and Rule2 category decoders.
%
% Right panel:
%   Non-rule task-modulated neurons.
%
% Each line connects the Sound-window and Early-window decoder AUC for one
% learning day. Paired statistics are computed across animals that have data
% in both windows.

if isempty(R) || height(R)==0
    h = figure('Name','Fig. 7E/I - Sound versus Early decoder AUC', ...
        'Position',[80 80 1100 480],'Visible','on');
    tiledlayout(1,2);
    nexttile; axis off; title('No decoder rows available');
    nexttile; axis off; title('No decoder rows available');
    return;
end

if ~isstring(R.animal),   R.animal   = string(R.animal);   end
if ~isstring(R.day),      R.day      = string(R.day);      end
if ~isstring(R.window),   R.window   = string(R.window);   end
if ~isstring(R.category), R.category = string(R.category); end

R = R(ismember(R.window, ["Sound","Early"]), :);

h = figure('Name','Fig. 7E/I - Sound versus Early decoder AUC', ...
    'Position',[80 80 1100 480], 'Visible','on');

tl = tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
titles = ["Rule-preferring neurons", "Non-rule task-modulated neurons"];
colors = lines(max(3, numel(days)));

for panel = 1:2
    ax = nexttile(tl, panel);
    hold(ax, 'on');
    box(ax, 'on');
    set(ax, 'XLim', [0.7 2.3]);
    xticks(ax, [1 2]);
    xticklabels(ax, {'Sound','Early'});
    ylabel(ax, 'Decoder AUC');
    yline(ax, 0.5, 'k--');
    title(ax, titles(panel));

    yAll = [];
    legH = gobjects(0);
    legLbl = strings(0);

    for di = 1:numel(days)
        dayName = string(days{di});

        if panel == 1
            [soundVals, earlyVals] = per_animal_rulepref(R, dayName);
        else
            [soundVals, earlyVals] = per_animal_nonrule(R, dayName);
        end

        muSound = mean(soundVals, 'omitnan');
        semSound = sem(soundVals);
        muEarly = mean(earlyVals, 'omitnan');
        semEarly = sem(earlyVals);

        if ~isfinite(muSound) && ~isfinite(muEarly)
            continue;
        end

        yAll = [yAll; muSound; muEarly]; %#ok<AGROW>

        thisColor = colors(di, :);
        hLine = errorbar(ax, [1 2], [muSound muEarly], [semSound semEarly], ...
            'o-', 'LineWidth', 1.5, 'MarkerSize', 6, 'Color', thisColor);

        legH(end+1) = hLine; %#ok<AGROW>
        legLbl(end+1) = dayName; %#ok<AGROW>

        pairedMask = isfinite(soundVals) & isfinite(earlyVals);
        nPairs = sum(pairedMask);

        pSignrank = NaN;
        pPermutation = NaN;
        medianDelta = NaN;

        if nPairs >= 2
            deltaAUC = soundVals(pairedMask) - earlyVals(pairedMask);
            medianDelta = median(deltaAUC, 'omitnan');

            try
                pSignrank = signrank(soundVals(pairedMask), earlyVals(pairedMask), 'tail', 'right');
            catch
                pSignrank = NaN;
            end

            pPermutation = paired_perm_right(deltaAUC, 10000);
        end

        pPlot = min([pSignrank pPermutation], [], 'omitnan');

        if isfinite(pPlot) && pPlot < 0.10
            yTop = max([muSound + semSound, muEarly + semEarly], [], 'omitnan');
            if ~isfinite(yTop)
                yTop = max([muSound, muEarly], [], 'omitnan');
            end
            if ~isfinite(yTop)
                yTop = 0.6;
            end
            draw_bracket(ax, 1, 2, yTop + 0.02, sprintf('%s (n=%d)', p2stars_(pPlot), nPairs));
        end

        if nPairs >= 1
            fprintf('[Fig 7E/I] %s | %s: n=%d, median Sound-Early Δ=%.3f, p_signrank=%.3g, p_perm=%.3g\n', ...
                titles(panel), dayName, nPairs, medianDelta, pSignrank, pPermutation);
        end
    end

    if ~isempty(yAll) && any(isfinite(yAll))
        lo = min([0.45; yAll(isfinite(yAll))]) - 0.02;
        hi = max([0.90; yAll(isfinite(yAll))]) + 0.02;
        ylim(ax, [lo hi]);
    else
        ylim(ax, [0.45 0.95]);
    end

    grid(ax, 'on');

    if ~isempty(legH)
        legend(ax, legH, legLbl, 'Location', 'eastoutside');
    end
end

sgtitle(tl, 'Decoder AUC: Sound versus Early windows', 'FontWeight','bold');
end

function [sVals, eVals] = per_animal_rulepref(R, dayName)
% Returns per-animal AUC vectors for Sound and Early for RULE-PREF:
% (within animal) mean of R1 and R2 when available.
    Rday = R(R.day==dayName & ismember(R.category,["Rule1","Rule2"]), :);
    animals = unique(Rday.animal);
    sVals = nan(numel(animals),1); eVals = nan(numel(animals),1);

    for i=1:numel(animals)
        a = animals(i);
        % Sound
        v1s = extract_auc(Rday, a, dayName, "Sound", "Rule1");
        v2s = extract_auc(Rday, a, dayName, "Sound", "Rule2");
        sVals(i) = mean([v1s v2s],'omitnan');
        % Early
        v1e = extract_auc(Rday, a, dayName, "Early", "Rule1");
        v2e = extract_auc(Rday, a, dayName, "Early", "Rule2");
        eVals(i) = mean([v1e v2e],'omitnan');
    end
end

function [sVals, eVals] = per_animal_nonrule(R, dayName)
% Returns per-animal AUC vectors for Sound and Early for NON-RULE.
    Rday = R(R.day==dayName & R.category=="NonRule", :);
    animals = unique(Rday.animal);
    sVals = nan(numel(animals),1); eVals = nan(numel(animals),1);

    for i=1:numel(animals)
        a = animals(i);
        sVals(i) = extract_auc(Rday, a, dayName, "Sound", "NonRule");
        eVals(i) = extract_auc(Rday, a, dayName, "Early", "NonRule");
    end
end

function v = extract_auc(T, animalName, dayName, windowName, categoryName)
% Safe single-value extractor (returns NaN if missing).
    idx = T.animal==animalName & T.day==dayName & T.window==windowName & T.category==categoryName;
    if any(idx)
        v = T.auc_mean(find(idx,1,'first'));
    else
        v = NaN;
    end
end


function p = paired_perm_right(diffs, B)
% Right-tailed paired permutation test on within-subject differences.
% H1: mean(diff) > 0. Flips sign of each subject's diff with p=0.5.
    diffs = diffs(:);
    diffs = diffs(isfinite(diffs));
    n = numel(diffs);
    if n < 2 || all(diffs==0), p = NaN; return; end
    obs = mean(diffs,'omitnan');
    if ~isfinite(obs), p = NaN; return; end
    sgn = (rand(B, n) > 0.5)*2 - 1;   % B×n of ±1
    nullMean = mean(sgn .* diffs', 2, 'omitnan');  % (B×n .* 1×n)' => B×1
    p = mean(nullMean >= obs);
end